spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/timerecorder
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 900
      validation-timeout: 900
      max-lifetime: 5000
      maximum-pool-size: 15

  sql:
    init:
      mode: always

  task:
    scheduling:
      pool:
        size: 1

app:
    queue: { capacity: 100 }

logging:
  level:
    com.example.time-recorder: INFO
    org.springframework.jdbc: WARN